### PR TITLE
Improved regex for decode method which fixes #19

### LINKED ISSUE #19: HTML chars without ending ; still decoded
The `.decode()` function is too aggressive as it decodes even incomplete HTML characters like in this example:

```javascript
var url = 'http://some-url.de/?param1=value1&lang=en';
console.log(require('html-entities').AllHtmlEntities.decode(url));
```

yields

```bash
http://some-url.de/?param1=value1⟨=en
```

This means, `&lang` (probably a not so rare URL parameter) is decoded as if it was `&lang;`, the character `⟨`.

### PR DESCRIPTION
**Pull request by dularion**
fixes https://github.com/mdevils/node-html-entities/issues/19

### CODE REVIEW

**Comment by mdevils** [comment]
Hello @dularion,
Thank you for your contribution!

Please try these pieces of code in your browser:

1:
```
(function(e){e.innerHTML = 'http://some-url.de/?param1=value1&lang=en'; console.log(e.textContent);})(document.createElement('div'));
```
2:
```
(function(e){e.innerHTML = 'http://some-url.de/?param1=value1&amp=en'; console.log(e.textContent);})(document.createElement('div'));
```

In the first case you can see that `&lang=` was preserved. In the second case `&amp=` was replaced with `&=`.

Your PR fixes the first case, but breaks the second one.

**Comment by dularion** [comment]
Are you saying that you **want** to replace `&amp`with `&`?  `&amp` is a faulty html-entity, as it does not contain the semicolon in the end.

**Comment by dularion** [comment]
Also, I don't quite understand your code snippet, shouldn't you be calling the `decode()` method? why are you looking att the textContent of divs

**Comment by mdevils** [comment]
I am just saying that when browser does html entities decoding it preserves `&lang=` as is while it turns `&amp=` into `&=` and turns `&lt=` into `&<=` (and actually many others). So `&lang=` rather looks like exception. I don't know the precise list of exceptions browser has.

> Also, I don't quite understand your code snippet, shouldn't you be calling the decode() method? why are you looking att the textContent of divs

This is just a short snippet which shows how *browser* decodes HTML Entities.

**Comment by dularion** [comment]
I dont know if you should mimick how the browser does or, should you? is that the goal of this library? shouldnt the goal be, to offer a one-size-fits-all for decoding/encoding?

**Comment by dularion** [comment]
Browsers, as I am sure yo uare aware, handle these things quite differently depending on the browser, version, and surely even OS. I don't think that that should be your inspiration...

**Comment by paddy-hack** [comment]
The [HTML5 spec](https://www.w3.org/TR/html5/syntax.html#character-references) is very clear about the requirement that entities end with a `;`.  The [HTML4 spec](https://www.w3.org/TR/1998/REC-html40-19980424/intro/sgmltut.html#character-entities) may not be quite as explicit but still says "they begin with a "&" sign and **end with a semi-colon (;)**" (emphasis added).

Quite frankly, I don't care what your browser-du-jour thinks is "a good stab at standards compliance".  I have HTML strings with raw URLs in a Node.js application that I need to decode and incorrectly decoding query fragments with `&lang=` and/or `&prod=` seriously broke *my* expectations :unamused: 

This really should be merged.

Other than that, thanks for a nice module :smile:

**Comment by paddy-hack** [comment]
I'd also be happy with a documented `strict` option that is disabled by default so as to not break backward compatibility.

**Comment by mdevils** [comment]
@paddy-hack 

> I'd also be happy with a documented strict option that is disabled by default so as to not break backward compatibility.

Great suggestion!

**Comment by mdevils** [comment]
@paddy-hack will you be able to provide a pull request for that?

**Pull request closed without merging**
